version: '3.4'

services:
  dormitorydb:
    container_name: dormitorydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DormitoryDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_dormitorydb:/var/lib/postgresql/data/