services:
  dormitorydb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  webapi:
    build:
      context: .
      dockerfile: Dockerfile   # Ścieżka do Twojego Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "5195:5195"
    environment:
      - ASPNETCORE_URLS=http://+:5195
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_dormitorydb: